import type { Post } from './types/post';

const PLACEHOLDER_IMAGES = [
  'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&h=600&fit=crop',
  'https://images.unsplash.com/photo-1634017839464-5c339ebe3579?w=800&h=600&fit=crop',
  'https://images.unsplash.com/photo-1618172193622-ae2d025f4032?w=800&h=600&fit=crop',
  'https://images.unsplash.com/photo-1558591710-4b4a1ae0f04d?w=800&h=600&fit=crop',
  'https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?w=800&h=600&fit=crop',
  'https://images.unsplash.com/photo-1605106702842-01a887a31122?w=800&h=600&fit=crop',
];

export const MOCK_POSTS: Post[] = [
  {
    id: 'disc-001',
    metadata: {
      localID: 'a3f8c1b2-9e4d-4f7a-b2c1-d8e9f0a1b2c3',
      versionID: 'v_1707823445123',
      authors: ['mia', 'jake'],
      title: 'New onboarding flow — mobile',
      tags: ['mobile', 'onboarding', 'v2'],
      team: 'Growth',
      project: 'Onboarding Redesign',
      urls: ['https://figma.com/proto/abc123'],
      assets: [
        { id: 'img-1', type: 'image', url: PLACEHOLDER_IMAGES[0], pendingCDN: false },
        { id: 'img-2', type: 'image', url: PLACEHOLDER_IMAGES[1], pendingCDN: false },
      ],
      commentPins: [],
    },
    body: 'Exploring a warmer, more personal onboarding experience for mobile. The key insight was reducing cognitive load in the first 30 seconds — we stripped out the account setup wall and moved it post-activation.',
    createdAt: '2026-02-13T14:30:00Z',
    commentCount: 5,
  },
  {
    id: 'disc-002',
    metadata: {
      localID: 'b4c9d2e3-0f5e-5a8b-c3d2-e9f0a1b2c3d4',
      versionID: 'v_1707823445124',
      authors: ['sara'],
      title: 'Dashboard data viz explorations',
      tags: ['dashboard', 'data-viz', 'exploration'],
      team: 'Platform',
      project: 'Analytics Dashboard',
      urls: ['https://figma.com/proto/def456', 'https://staging.example.com/dashboard'],
      assets: [
        { id: 'img-3', type: 'image', url: PLACEHOLDER_IMAGES[2], pendingCDN: false },
        { id: 'img-4', type: 'image', url: PLACEHOLDER_IMAGES[3], pendingCDN: false },
        { id: 'img-5', type: 'image', url: PLACEHOLDER_IMAGES[4], pendingCDN: false },
      ],
      commentPins: [],
    },
    body: 'Three directions for the analytics dashboard redesign. Direction A leans into density, Direction B prioritizes scannability, Direction C goes editorial with larger type and more whitespace.',
    createdAt: '2026-02-12T09:15:00Z',
    commentCount: 12,
  },
  {
    id: 'disc-003',
    metadata: {
      localID: 'c5d0e3f4-1a6f-6b9c-d4e3-f0a1b2c3d4e5',
      versionID: 'v_1707823445125',
      authors: ['alex', 'mia'],
      title: 'Brand refresh — icon system',
      tags: ['brand', 'icons', 'system'],
      team: 'Design Systems',
      project: 'Brand Refresh 2026',
      urls: [],
      assets: [
        { id: 'img-6', type: 'image', url: PLACEHOLDER_IMAGES[5], pendingCDN: false },
      ],
      commentPins: [],
    },
    body: 'Proposing a shift from outlined to duotone icons. The new system uses two weights — a thicker stroke for primary actions and a lighter stroke for secondary/decorative use.',
    createdAt: '2026-02-11T16:45:00Z',
    commentCount: 8,
  },
  {
    id: 'disc-004',
    metadata: {
      localID: 'd6e1f4a5-2b7a-7c0d-e5f4-a1b2c3d4e5f6',
      versionID: 'v_1707823445126',
      authors: ['jake'],
      title: 'Settings page redesign — accessibility audit',
      tags: ['settings', 'a11y', 'redesign'],
      team: 'Platform',
      project: 'Settings v3',
      urls: ['https://figma.com/proto/ghi789'],
      assets: [
        { id: 'img-7', type: 'image', url: PLACEHOLDER_IMAGES[0], pendingCDN: false },
        { id: 'img-8', type: 'image', url: PLACEHOLDER_IMAGES[3], pendingCDN: false },
      ],
      commentPins: [],
    },
    body: 'After the accessibility audit flagged 23 issues on the current settings page, this redesign addresses contrast ratios, focus management, and screen reader navigation. Every interactive element now meets WCAG 2.2 AA.',
    createdAt: '2026-02-10T11:20:00Z',
    commentCount: 3,
  },
  {
    id: 'disc-005',
    metadata: {
      localID: 'e7f2a5b6-3c8b-8d1e-f6a5-b2c3d4e5f6a7',
      versionID: 'v_1707823445127',
      authors: ['sara', 'alex'],
      title: 'Empty states — illustration system',
      tags: ['illustration', 'empty-states', 'system'],
      team: 'Design Systems',
      project: 'Illustration Library',
      urls: [],
      assets: [
        { id: 'img-9', type: 'image', url: PLACEHOLDER_IMAGES[1], pendingCDN: false },
        { id: 'img-10', type: 'image', url: PLACEHOLDER_IMAGES[4], pendingCDN: false },
        { id: 'img-11', type: 'image', url: PLACEHOLDER_IMAGES[5], pendingCDN: false },
      ],
      commentPins: [],
    },
    body: 'A cohesive set of empty state illustrations that feel warm without being infantilizing. Using a limited palette derived from our brand colors with hand-drawn line work.',
    createdAt: '2026-02-09T13:00:00Z',
    commentCount: 15,
  },
];
